### ISSUE TITLE
What is your favorite nintendo game? And what is your favorite picture, and thing about a furret?

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/ama#3]
# What is your favorite nintendo game? And what is your favorite picture of, and thing about a furret?

Thanks!!

**Comment by RayhanADev** [comment]
Hiya!
Okay my **favorite nintendo game is probably Pokémon Diamond** (or Pearl, they're both basically the same) partly because it's fun, but also because **it has the most game breaking glitches** (in my opinion) of all the Pokémon games!

My **favorite picture of a Furret...** oh here we go:
![](https://i.imgflip.com/475769.jpg)

~~Rayquaza get rekt~~

Truthfully my **favorite thing about Furrets is how even Game Freak and Pokémon don't agree with it's height**. Apparently **Furret is taller than a Charizard, yet in all games Furret is portrayed as smaller than the main character** which I find hilarious! They're also so cute!

**Comment by darkdarcool** [comment]
cool!

**Comment by darkdarcool** [comment]
my favorite nintendo game is zelda botw and splatoon 2(hyped for splatoon 3)! (yea and the pokemon thing makes no sense)

**Comment by willcatmeow** [comment]
furret is measured head to tail even though it's furret's height so i guess furret is a long boi

**Comment by darkdarcool** [comment]
He is like a cross of snake and furret

**Comment by TheQuackyDuck** [comment]
> He is like a cross of snake and furret

yes.
