### ISSUE TITLE
How do you make a issue template? Why don't you join @Repl-it-Coders?

### ISSUE THREAD

**Issue by IcingHackz** [RayhanADev/ama#9]
1. I'm just getting used to github's pog features so yeah. I dunno how to make a issue template...can you teach me?

2. Why don't you join @Repl-it-Coders? You are a replit coder so why not join. Ping @whippingdot (sry for the ping) if you want to join. :)

**Comment by RayhanADev** [comment]
G'day :D

To make issue tempates, go to `https://github.com/[your-username]/[repository]/issues/templates/edit` and it will guide you through making one or you can use presets :).

I'm not really joining the organization because I join very few, really just ones where I do something important (this is my "professional" profile after all).

**Comment by IcingHackz** [comment]
Got it thx!

Oh! Ok np!

**Comment by whippingdot** [comment]
hey ray tink about it. I know its ur professional profile but one group doesn't really matter...

**Comment by EpicGamer007** [comment]
Honestly, it would be great to have you. And you can make it so that people cannot see that you are in the organization (this is by default normally)

**Comment by RayhanADev** [comment]
@EpicGamer007 @whippingdot @IcingHackz I've considered it...
I'll join :). Send me an invite lol.

**Comment by whippingdot** [comment]
Yay 🥳🥳

**Comment by whippingdot** [comment]
ey @RayhanADev I am adding someone called [willcatmeow](https://github.com/willcatmeow) and on his website it says he likes furrets OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by whippingdot** [comment]
BTW go to https://github.com/Repl-it-Coders to join the org

**Comment by coolcoder-js** [comment]
Could I join?

**Comment by RayhanADev** [comment]
@coolcoder-js I sent you an invite :)

**Comment by whippingdot** [comment]
Ummmm Rayhan usually people would ask me but because I trust you, it's ok. Also I know coolcoderjs so it's fine. Just make sure you know their replit username, check that username, and check if they have been on replit for at least one or two months because otherwise they might be one person I got banned like neonking and they might try to mess everything up

**Comment by RayhanADev** [comment]
@whippingdot sure, I just went and invited @coolcoder-js since they're a kewl person lol

**Comment by coolcoder-js** [comment]
lol tnx

**Comment by IcingHackz** [comment]
xD i didn't even see any of these comments after i closed the issue !!!
